version: '3.4'

services:
  accountandjwt.authorizationservice:
    image: ${DOCKER_REGISTRY-}accountandjwtauthorizationservice
    build:
      context: .
      dockerfile: AccountAndJwt.AuthorizationService/Dockerfile
    environment:
    - DefaultConnection=Data Source=host.docker.internal\SQLEXPRESS;Initial Catalog=AccountAndJwtDbDev;Integrated Security=False;User Id=docker;Password=JBZAN9CdjR5S3SKlr15b

  accountandjwt.ui:
    image: ${DOCKER_REGISTRY-}accountandjwtui
    build:
      context: .
      dockerfile: AccountAndJwt.Ui/Dockerfile
    ports:
      - 5230:80
      - 7230:443